global:
  exportedTagsOnMetrics:
    AWS/ES:
      - Client
      - Environment
    AWS/EBS:
      - VolumeId
discovery:
  - namespace: AWS/ES
    regions:
      - eu-west-1
    metrics:
      - name: FreeStorageSpace
        statistics:
        - Sum
        period: 60
        length: 600
      - name: ClusterStatus.green
        statistics:
        - Minimum
        period: 60
        length: 600
      - name: ClusterStatus.yellow
        statistics:
        - Maximum
        period: 60
        length: 600
      - name: ClusterStatus.red
        statistics:
        - Maximum
        period: 60
        length: 600
  - namespace: AWS/ELB
    regions:
      - eu-west-1
    filterTags:
      - Key: type
        Value: test
    length: 900
    delay: 120
    metrics:
      - name: HealthyHostCount
        statistics:
        - Minimum
        period: 600
        length: 600 #(this will be ignored)
      - name: HTTPCode_Backend_4XX
        statistics:
        - Sum
        period: 60
        length: 900 #(this will be ignored)
        delay: 300 #(this will be ignored)
        nilToZero: true
  - namespace: AWS/ApplicationELB
    regions:
      - eu-west-1
    filterTags:
      - Key: kubernetes.io/service-name
        Value: .*
    metrics:
      - name: HealthyHostCount
        statistics: [Maximum]
        period: 60
        length: 600
  - namespace: AWS/VPN
    regions:
      - eu-west-1
    filterTags:
      - Key: kubernetes.io/service-name
        Value: .*
    metrics:
      - name: TunnelState
        statistics:
        - p90
        period: 60
        length: 300
  - namespace: AWS/Kinesis
    regions:
      - eu-west-1
    metrics:
      - name: PutRecords.Success
        statistics:
        - Sum
        period: 60
        length: 300
  - namespace: AWS/S3
    regions:
      - eu-west-1
    filterTags:
      - Key: type
        Value: public
    metrics:
      - name: NumberOfObjects
        statistics:
          - Average
        period: 86400
        length: 172800
      - name: BucketSizeBytes
        statistics:
          - Average
        period: 86400
        length: 172800
  - namespace: AWS/EBS
    regions:
      - eu-west-1
    filterTags:
      - Key: type
        Value: test
    metrics:
      - name: BurstBalance
        statistics:
        - Minimum
        period: 600
        length: 600
        addCloudwatchTimestamp: true
  - namespace: AWS/Kafka
    regions:
      - eu-west-1
    filterTags:
      - Key: env
        Value: dev
    metrics:
      - name: BytesOutPerSec
        statistics:
        - Average
        period: 600
        length: 600
static:
  - namespace: AWS/AutoScaling
    name: must_be_set
    regions:
      - eu-west-1
    dimensions:
     - name: AutoScalingGroupName
       value: Test
    customTags:
      - Key: CustomTag
        Value: CustomValue
    metrics:
      - name: GroupInServiceInstances
        statistics:
        - Minimum
        period: 60
        length: 300
